apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-snapshot-validation
  namespace: {{ .Release.Namespace }}
  labels:
    app: snapshot-validation
    high-availability-config.resources.gardener.cloud/type: server
spec:
  replicas: {{ .Values.csiSnapshotValidationWebhook.replicas }}
  selector:
    matchLabels:
      app: snapshot-validation
  template:
    metadata:
      annotations:
{{- if .Values.csiSnapshotValidationWebhook.podAnnotations }}
{{ toYaml .Values.csiSnapshotValidationWebhook.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: snapshot-validation
        networking.gardener.cloud/from-shoot-apiserver: allowed
        networking.gardener.cloud/to-dns: allowed
        networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
    spec:
      automountServiceAccountToken: false
      priorityClassName: gardener-system-200
      containers:
      - name: openstack-csi-snapshot-validation
        image: {{ index .Values.images "csi-snapshot-validation-webhook" }}
        imagePullPolicy: IfNotPresent
        args:
          - --tls-cert-file=/etc/csi-snapshot-validation/tls.crt
          - --tls-private-key-file=etc/csi-snapshot-validation/tls.key
          - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
        ports:
        - containerPort: 443
{{- if .Values.csiSnapshotValidationWebhook.resources }}
        resources:
{{ toYaml .Values.csiSnapshotValidationWebhook.resources | indent 10 }}
{{- end }}
        volumeMounts:
          - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
            name: kubeconfig
            readOnly: true
          - name: csi-snapshot-validation
            mountPath: /etc/csi-snapshot-validation
            readOnly: true
      volumes:
        - name: kubeconfig
          projected:
            defaultMode: 420
            sources:
              - secret:
                  items:
                    - key: kubeconfig
                      path: kubeconfig
                  name: {{ .Values.global.genericTokenKubeconfigSecretName }}
                  optional: false
              - secret:
                  items:
                    - key: token
                      path: token
                  name: shoot-access-csi-snapshot-validation
                  optional: false
        - name: csi-snapshot-validation
          secret:
            secretName: {{ .Values.csiSnapshotValidationWebhook.secrets.server }}

