apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: csi-snapshot-validation
  namespace: {{ .Release.Namespace }}
  labels:
    app: snapshot-validation
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: snapshot-validation
  unhealthyPodEvictionPolicy: AlwaysAllow