---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: csi-snapshot-controller-vpa
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: csi-snapshot-controller
      minAllowed:
        memory: 25Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csi-snapshot-controller
  updatePolicy:
    updateMode: Auto
