# see https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    non-gardener-dependencies:
      applies-to: "version-updates"
      patterns:
      - "*"
      exclude-patterns:
      - "github.com/gardener*"
      - "github.com/gophercloud/*"
    provider-sdk-dependencies:
      applies-to: "version-updates"
      patterns:
      - "github.com/gophercloud/*"
  ignore:
  - dependency-name: "k8s.io/*"
  - dependency-name: "github.com/gardener/etcd-druid/*"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
