---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "csi-driver-node.extensionsGroup" . }}.{{ include "csi-driver-node.name" . }}.csi-driver-node
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
  - hostPath
  - secret
  hostNetwork: true
  hostPorts:
  - max: 9808
    min: 9808
  allowedHostPaths:
  - pathPrefix: /var/lib/kubelet
  - pathPrefix: /dev
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
