apiVersion: v1
kind: Service
metadata:
  name: machine-controller-manager
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.resources.gardener.cloud/from-all-scrape-targets-allowed-ports: '[{"port":{{ .Values.metricsPort }},"protocol":"TCP"}]'
    # TODO: This label approach is deprecated and no longer needed in the future. Remove them as soon as gardener/gardener@v1.75 has been released.
    networking.resources.gardener.cloud/from-policy-pod-label-selector: all-scrape-targets
    networking.resources.gardener.cloud/from-policy-allowed-ports: '[{"port":{{ .Values.metricsPort }},"protocol":"TCP"}]'
  labels:
    app: kubernetes
    role: machine-controller-manager
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.metricsPort }}
    protocol: TCP
  selector:
    app: kubernetes
    role: machine-controller-manager
