apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels: {{ include "labels" . | nindent 4 }}
data:
  config.yaml: |
    ---
    apiVersion: openstack.provider.extensions.config.gardener.cloud/v1alpha1
    kind: ControllerConfiguration

{{- if .Values.config.clientConnection }}
    clientConnection:
      acceptContentTypes: {{ required ".Values.config.clientConnection.acceptContentTypes is required" .Values.config.clientConnection.acceptContentTypes }}
      contentType: {{ required ".Values.config.clientConnection.contentType is required" .Values.config.clientConnection.contentType }}
      qps: {{ required ".Values.config.clientConnection.qps is required" .Values.config.clientConnection.qps }}
      burst: {{ required ".Values.config.clientConnection.burst is required" .Values.config.clientConnection.burst }}
{{- end }}
    etcd:
      storage:
        className: {{ .Values.config.etcd.storage.className }}
        capacity: {{ .Values.config.etcd.storage.capacity }}
      {{- if .Values.config.etcd.events }}
      events:
        className: {{ .Values.config.etcd.events.className }}
        capacity: {{ .Values.config.etcd.events.capacity }}
      {{- end }}
{{- if .Values.config.etcd.backup }}
      backup: {{- toYaml .Values.config.etcd.backup | nindent 8 }}
{{- end }}
    bastionConfig:
      imageRef:  {{ .Values.config.bastionConfig.imageRef }}
      flavorRef: {{ .Values.config.bastionConfig.flavorRef }}
