images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer
  tag: "0.20.0"
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "v0.27.0"
- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes/cloud-provider-openstack
  repository: k8s.gcr.io/hyperkube
  targetVersion: "< 1.15"
- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes/cloud-provider-openstack
  repository: k8scloudprovider/openstack-cloud-controller-manager
  tag: "v1.17.0"
  targetVersion: ">= 1.15"
