images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer-openstack
  tag: "v2.16.0"

- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes/cloud-provider-openstack
  repository: k8scloudprovider/openstack-cloud-controller-manager
  tag: "v1.17.0"
  targetVersion: "< 1.18"
- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes/cloud-provider-openstack
  repository: k8scloudprovider/openstack-cloud-controller-manager
  tag: "v1.21.0"
  targetVersion: ">= 1.18, < 1.22"
- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes/cloud-provider-openstack
  repository: k8scloudprovider/openstack-cloud-controller-manager
  tag: "v1.22.0"
  targetVersion: "1.22.x"
- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes/cloud-provider-openstack
  repository: k8scloudprovider/openstack-cloud-controller-manager
  tag: "v1.23.1"
  targetVersion: ">= 1.23"

- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "v0.44.1"
- name: machine-controller-manager-provider-openstack
  sourceRepository: github.com/gardener/machine-controller-manager-provider-openstack
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager-provider-openstack
  tag: "v0.9.0"

- name: csi-driver-cinder
  sourceRepository: github.com/kubernetes/cloud-provider-openstack
  repository: docker.io/k8scloudprovider/cinder-csi-plugin
  tag: "v1.19.0"
  targetVersion: "< 1.20"
- name: csi-driver-cinder
  sourceRepository: github.com/kubernetes/cloud-provider-openstack
  repository: docker.io/k8scloudprovider/cinder-csi-plugin
  tag: "v1.20.0"
  targetVersion: "1.20.x"
- name: csi-driver-cinder
  sourceRepository: github.com/kubernetes/cloud-provider-openstack
  repository: docker.io/k8scloudprovider/cinder-csi-plugin
  tag: "v1.21.0"
  targetVersion: "1.21.x"
- name: csi-driver-cinder
  sourceRepository: github.com/kubernetes/cloud-provider-openstack
  repository: docker.io/k8scloudprovider/cinder-csi-plugin
  tag: "v1.22.0"
  targetVersion: "1.22.x"
- name: csi-driver-cinder
  sourceRepository: github.com/kubernetes/cloud-provider-openstack
  repository: docker.io/k8scloudprovider/cinder-csi-plugin
  tag: "v1.23.0"
  targetVersion: ">= 1.23"

- name: csi-provisioner
  sourceRepository: github.com/kubernetes-csi/external-provisioner
  repository: k8s.gcr.io/sig-storage/csi-provisioner
  tag: "v2.0.4"
- name: csi-attacher
  sourceRepository: github.com/kubernetes-csi/external-attacher
  repository: k8s.gcr.io/sig-storage/csi-attacher
  tag: "v3.3.0"
- name: csi-snapshotter
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: k8s.gcr.io/sig-storage/csi-snapshotter
  tag: "v3.0.3"
- name: csi-snapshot-controller
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: k8s.gcr.io/sig-storage/snapshot-controller
  tag: "v3.0.3"
- name: csi-snapshot-validation-webhook
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: k8s.gcr.io/sig-storage/snapshot-validation-webhook
  tag: "v3.0.3"
- name: csi-resizer
  sourceRepository: github.com/kubernetes-csi/external-resizer
  repository: k8s.gcr.io/sig-storage/csi-resizer
  tag: "v0.5.0"
- name: csi-node-driver-registrar
  sourceRepository: github.com/kubernetes-csi/node-driver-registrar
  repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  tag: "v2.0.1"
- name: csi-liveness-probe
  sourceRepository: github.com/kubernetes-csi/livenessprobe
  repository: k8s.gcr.io/sig-storage/livenessprobe
  tag: "v2.3.0"
