apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "name" . }}
webhooks:
- name: validation.openstack.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shoots
  failurePolicy: Fail
  objectSelector: {}
  namespaceSelector: {}
  clientConfig:
    {{- if .Values.global.virtualGarden.enabled }}
    url: {{ printf "https://%s.%s/webhooks/validate" (include "name" .) (.Release.Namespace) }}
    {{- else }}
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "name" . }}
      path: /webhooks/validate
    {{- end }}
    caBundle: {{ required ".Values.webhookConfig.caBundle is required" (b64enc .Values.global.webhookConfig.caBundle) }}
