apiVersion: v1
description: A Helm chart to deploy the gardener-extension-admission-openstack runtime related resources
name: admission-openstack-runtime
version: 0.1.0
sources:
- https://github.com/gardener/gardener-extension-provider-openstack
