kubernetesVersion: 0.0.1
#[Global]
authUrl: fooURL
domainName: fooDomain
tenantName: fooTenant
username: barUser
password: barPass
region: eu
# [LoadBalancer]
lbProvider: foobar
# floatingNetworkID: foo-bar-123
# floatingSubnetID: asd12345
# floatingSubnetName: "*abc*"
# floatingSubnetTags: tag1,tag2
# subnetID: foo-bar-123
# [Metadata]
dhcpDomain: foobar
requestTimeout: 2s
useOctavia: false
rescanBlockStorageOnResize: false
# nodeVolumeAttachLimit: 25
# floatingClasses:
# - name: A
#   floatingNetworkID: "1234"
#   floatingSubnetID: "12345"
#   subnetID: a464545
# - name: B
#   floatingSubnetID: asd12345
#   subnetID: asd464545
# - name: C
#   floatingNetworkID: "1234"
#   floatingSubnetName: "*abc*"
# - name: D
#   floatingNetworkID: "1234"
#   floatingSubnetTags: tag1,tag2
