name: Integration-Tests
description: |
  Runs Integration tests using TestMachinery

on:
  push:
    branches:
      - master
  workflow_dispatch:
  workflow_call:
    inputs:
      skip-integration-tests:
        type: boolean
        default: false
        description: 'Skip running integration tests.'

jobs:
  integrationtest:
    permissions:
      id-token: write
      contents: read
    uses: gardener/cc-utils/.github/workflows/run-testmachinery-tests.yaml@master
    with:
      test-command: |
        ${testrunner_run} \
         --no-execution-group \
         --testrun-prefix tm-extension-openstack- \
         --timeout=3600 \
         --testruns-chart-path=.ci/testruns/default \
         --set revision=$(git rev-parse @)

  skip-tests:
    if: ${{ inputs.skip-integration-tests }}
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Skip Integration Tests
        run: echo "Skipping Integration Tests as per input parameter."
